site_name: Nagao Engineering Encyclopedia

theme:
  name: material

markdown_extensions:
  - tables
  - admonition
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
 

extra:
  math: true

nav:
  - Home: index.md
  - Guide: guide.md
  - Teste: teste.md
  
  - Mathematics:
      - Logic: mathematics/logica.md
      - Conjuntos: mathematics/conjuntos.md
      - Relações: mathematics/relacoes.md
      - Funções: mathematics/funcoes.md
      - Indução: mathematics/inducao.md
      - Boa Ordenação: mathematics/boaordenacao.md
      - Prova por Contradição: mathematics/contradicao.md
      - Provas Construtivas: mathematics/construtiva.md
      - Prova de Existencia: mathematics/existencia.md

  - C language:
      - C Language Medium Level: clang/medium.md
      - C Language Advanced Level: clang/advanced
